// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABE0ujy0VqEB7y_zZc1NmsKPAfnjlWFfM',
    appId: '1:670003911850:web:b41ce43eb35b36448004d3',
    messagingSenderId: '670003911850',
    projectId: 'chat-app-3f311',
    authDomain: 'chat-app-3f311.firebaseapp.com',
    storageBucket: 'chat-app-3f311.appspot.com',
    measurementId: 'G-6YVFDMZXPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxLTYtUh9NMv5aiYBGztod_CAn9R7UI8',
    appId: '1:670003911850:android:0f53df7b8b10eed28004d3',
    messagingSenderId: '670003911850',
    projectId: 'chat-app-3f311',
    storageBucket: 'chat-app-3f311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCeflwtvzPYyaVN3p6ytsCi9C7Kx_WZJ8',
    appId: '1:670003911850:ios:6e00cd0967d751778004d3',
    messagingSenderId: '670003911850',
    projectId: 'chat-app-3f311',
    storageBucket: 'chat-app-3f311.appspot.com',
    iosClientId: '670003911850-ed55tbr5fb7pj7vb24odnduc2e09p56l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCeflwtvzPYyaVN3p6ytsCi9C7Kx_WZJ8',
    appId: '1:670003911850:ios:b2cfb142935d18be8004d3',
    messagingSenderId: '670003911850',
    projectId: 'chat-app-3f311',
    storageBucket: 'chat-app-3f311.appspot.com',
    iosClientId: '670003911850-bmfedh04ioc2b1q1ogoatsrjsgbvvi60.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingPractice.RunnerTests',
  );
}
